service: eventbridge-example

package:
  exclude:
    - mfa.sh
    - node_modules/**
    - package.json
    - __tests__/**

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "events:*"
      Resource:
        Fn::GetAtt:
          - EventBridge
          - Arn
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:eventbridge-example-dev-service2
        - arn:aws:s3:::example-dev-thumbnail-bucket/*

functions:
  service1:
    handler: service1.handler
  service2:
    handler: service2.handler
    role: EventRole
    events:
      - eventBridge:
          eventBus: arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/event-bridge
          pattern:
            source:
              - custom.service2_event

resources:
  Resources:
    SqsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqsQueue

    EventBridge:
      Type: AWS::Events::EventBus
      Properties:
        Name: event-bridge

    EventBridgeRule:
      Type: AWS::Events::Rule
      Properties:
        EventBusName: event-bridge
        EventPattern:
          source:
            - custom.service2_event
        Targets:
          - Id: 1
            Arn:
              Fn::GetAtt:
                - SqsQueue
                - Arn
          - Id: 2
            Arn:
              Fn::GetAtt: [Service2LambdaFunction, Arn]

    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: example-dev-thumbnail-bucket

    EventRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "EventRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
                  - "s3.amazonaws.com"
                  - "events.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          - arn:aws:iam::aws:policy/AmazonS3FullAccess
